---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalpa/angular-cli

inputs:
- name: mg-tests-demo

outputs:
- name: mg-tests-output

run:
  path: sh
  args:
    - -exc
    - |
      cd mg-tests-demo
      npm install
      npm run-script karmatest
