---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalpa/angular-cli

inputs:
- name: mg-tests-demo

outputs:
- name: compiled-mg-tests-demo

run:
  path: sh
  args:
    - -exc
    - |
      cd mg-tests-demo
      npm install
      ng build --prod --aot
      cp -r dist/* ../compiled-mg-tests-demo/
